name: tempscale
summary: CLI Tool
description: |
  A CLI tool that converts temperature scale.
version: "0.1.1"
grade: stable
base: core20
confinement: strict
apps:
  baseshift:
    command: bin/tempscale
parts:
  baseshift:
    plugin: go
    source-type: git
    source: https://github.com/kentlouisetonino/tempscale.git
